name: another_yes_no_flutter_application
description: "Another sample Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
